package com.example.geennews.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jy.beans.MyLikeBeans;

import com.example.geennews.dao.MyLikeBeansDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myLikeBeansDaoConfig;

    private final MyLikeBeansDao myLikeBeansDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myLikeBeansDaoConfig = daoConfigMap.get(MyLikeBeansDao.class).clone();
        myLikeBeansDaoConfig.initIdentityScope(type);

        myLikeBeansDao = new MyLikeBeansDao(myLikeBeansDaoConfig, this);

        registerDao(MyLikeBeans.class, myLikeBeansDao);
    }
    
    public void clear() {
        myLikeBeansDaoConfig.clearIdentityScope();
    }

    public MyLikeBeansDao getMyLikeBeansDao() {
        return myLikeBeansDao;
    }

}
